/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Middlewares.FieldsValidator;
import Model.Book;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Ibarra
 */
public class AddBookForm extends javax.swing.JFrame {

    FieldsValidator validator = new FieldsValidator();
    String origin_path = "";
    String destination_path = "";

    public AddBookForm() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        background = new javax.swing.JPanel();
        book_id = new javax.swing.JTextField();
        book_title = new javax.swing.JTextField();
        book_year = new javax.swing.JTextField();
        book_author = new javax.swing.JTextField();
        book_category = new javax.swing.JTextField();
        book_edition = new javax.swing.JTextField();
        book_language = new javax.swing.JTextField();
        lbl_Id = new javax.swing.JLabel();
        lbl_title = new javax.swing.JLabel();
        lbl_year = new javax.swing.JLabel();
        lbl_author = new javax.swing.JLabel();
        lbl_category = new javax.swing.JLabel();
        lbl_edition = new javax.swing.JLabel();
        lbl_language = new javax.swing.JLabel();
        btn_submit = new CustomComponents.Button();
        jLabel1 = new javax.swing.JLabel();
        btn_pdf_selector = new javax.swing.JButton();
        lbl_language1 = new javax.swing.JLabel();
        book_stock = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AGREGA TU LIBRO");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        book_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                book_idKeyTyped(evt);
            }
        });

        book_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_yearActionPerformed(evt);
            }
        });
        book_year.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                book_yearKeyTyped(evt);
            }
        });

        book_edition.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                book_editionKeyTyped(evt);
            }
        });

        lbl_Id.setText("ID LIBRO");

        lbl_title.setText("TITULO");

        lbl_year.setText("AÑO DE PUBLICACION");

        lbl_author.setText("AUTOR");

        lbl_category.setText("CATEGORIA");

        lbl_edition.setText("EDICION");

        lbl_language.setText("IDIOMA");

        btn_submit.setBackground(new java.awt.Color(153, 255, 255));
        btn_submit.setText("AGREGAR");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        jLabel1.setText("AGREGA TU LIBRO");

        btn_pdf_selector.setText("Agregar PDF");
        btn_pdf_selector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pdf_selectorActionPerformed(evt);
            }
        });

        lbl_language1.setText("Stock");

        book_stock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                book_stockKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btn_pdf_selector)
                        .addGap(36, 36, 36)
                        .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(book_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_year)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_language1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbl_category, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_author, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_edition, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_language, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(book_id, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book_title, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book_year, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book_author, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book_category, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book_edition, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book_language, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Id))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_title))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_year))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book_author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_author))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_category))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book_edition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_edition))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book_language, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_language))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_language1))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pdf_selector))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed

        try {
            Object[] FIELDS = {
                this.book_id,
                this.book_author,
                this.book_category,
                this.book_edition,
                this.book_language,
                this.book_title,
                this.book_year,
                this.book_stock
            };

            if (!validator.validateBlank(FIELDS)) {
                JOptionPane.showMessageDialog(this, "Rellene todos los campos");
                return;
            }

            Book book;
            book = new Book(
                    Integer.parseInt(book_id.getText()),
                    book_title.getText(),
                    Integer.parseInt(book_year.getText()),
                    book_author.getText(),
                    book_category.getText(),
                    Integer.parseInt(book_edition.getText()),
                    book_language.getText(),
                    Integer.parseInt(this.book_stock.getText())
            );

            try {
                book.save();
                MainView.showJpanel(new BooksView(true));

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "ID de libro Existente");
                return;
            }

            System.out.println("Book saved");
            BooksView.updateTable();

            JOptionPane.showMessageDialog(this, "EL Libro Fue Agregado Correctamente");
        } catch (SQLException ex) {
            Logger.getLogger(AddBookForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_submitActionPerformed

    private void book_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_book_idKeyTyped
        validator.onlyNumbers(evt);
    }//GEN-LAST:event_book_idKeyTyped

    private void book_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book_yearActionPerformed

    private void book_yearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_book_yearKeyTyped
        validator.onlyNumbers(evt);
        int year = this.book_year.getText().length();

        if (year > 3) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "El año solo puede tener 4 caracteres");
            return;
        }

    }//GEN-LAST:event_book_yearKeyTyped

    private void book_editionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_book_editionKeyTyped
        validator.onlyNumbers(evt);
    }//GEN-LAST:event_book_editionKeyTyped

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        BooksView.btn_menu_add.setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    private void btn_pdf_selectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pdf_selectorActionPerformed

        JFileChooser filechoose = new JFileChooser();
        int option = filechoose.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            origin_path = filechoose.getSelectedFile().getAbsolutePath();
            destination_path = BooksView.books_path + book_id.getText() + ".pdf";
            btn_pdf_selector.setText("Tengo la info ;)");
        }

    }//GEN-LAST:event_btn_pdf_selectorActionPerformed

    private void book_stockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_book_stockKeyTyped
        validator.onlyNumbers(evt);
    }//GEN-LAST:event_book_stockKeyTyped

    int getStockById(int id) {
        int stock = 0;
        for (int i = 0; i < BooksView.model_table_books.getRowCount(); i++) {

            try {

                int id_table = Integer.parseInt(BooksView.model_table_books.getValueAt(i, 0).toString());

                if (id == id_table) {
                    stock = Integer.parseInt(BooksView.model_table_books.getValueAt(i, 7).toString());
                }

                System.out.println(stock);
            } catch (NullPointerException e) {
                return 0;
            }

        }

        return stock;

    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JTextField book_author;
    private javax.swing.JTextField book_category;
    private javax.swing.JTextField book_edition;
    private javax.swing.JTextField book_id;
    private javax.swing.JTextField book_language;
    private javax.swing.JTextField book_stock;
    private javax.swing.JTextField book_title;
    private javax.swing.JTextField book_year;
    private javax.swing.JButton btn_pdf_selector;
    private CustomComponents.Button btn_submit;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_Id;
    private javax.swing.JLabel lbl_author;
    private javax.swing.JLabel lbl_category;
    private javax.swing.JLabel lbl_edition;
    private javax.swing.JLabel lbl_language;
    private javax.swing.JLabel lbl_language1;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_year;
    // End of variables declaration//GEN-END:variables
}
