/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ibarra
 */
public class BooksView extends javax.swing.JPanel {
    

    public static DefaultTableModel model_table_books;
    boolean isAdmin;
    public static String user_name = System.getProperty("user.name");
    public static String books_path = "C:\\Users\\" + user_name + "\\Documents\\BookLIB\\";
    public BooksView(boolean isAdmin) {
        initComponents();
        this.setLocation(WIDTH, WIDTH);
        model_table_books = (DefaultTableModel) this.tbl_books.getModel();
        initializePopUpMenu();
        this.isAdmin = isAdmin;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pp_menu_table = new javax.swing.JPopupMenu();
        background = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_books = new javax.swing.JTable();
        btn_menu_add = new CustomComponents.KButton();

        tbl_books.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "El Principito", "2016", "Antoine de Saint-Exupery", "Ficcion", "1", "ES", "1"}
            },
            new String [] {
                "ID LIBRO", "TITULO", "AÑO PUBLICACION", "AUTOR", "CATEGORIA", "EDICION", "IDIOMA", "EXISTENCIA"
            }
        ));
        tbl_books.setToolTipText("");
        jScrollPane1.setViewportView(tbl_books);

        btn_menu_add.setText("Agregar Libro");
        btn_menu_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(btn_menu_add, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 456, Short.MAX_VALUE)))
                .addContainerGap())
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btn_menu_add, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_menu_addActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_menu_addActionPerformed
        if (!isAdmin){JOptionPane.showMessageDialog(this, "No tienes Permiso Para Ver Ésto");return;}
        
        btn_menu_add.setEnabled(false);
        AddBookForm addForm = new AddBookForm();
        addForm.setVisible(true);
    }// GEN-LAST:event_btn_menu_addActionPerformed

    public void initializePopUpMenu() {
        JMenuItem viewPDF = new JMenuItem("Ver PDF");
        pp_menu_table.add(viewPDF);

        tbl_books.setComponentPopupMenu(pp_menu_table);

        viewPDF.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                try {
                    int book_id_selected = Integer
                            .parseInt(tbl_books.getValueAt(tbl_books.getSelectedRow(), 0).toString());

                    File path = new File("C:\\Users\\"+user_name+"\\Documents\\BookLib\\"
                            + book_id_selected + ".pdf");
                    if (!path.exists()) {
                        JOptionPane.showMessageDialog(null, "No se encontro el archivo");
                        return;
                    }
                    Desktop.getDesktop().open(path);

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Selecciona el libro con click derecho");
                }

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    public static CustomComponents.KButton btn_menu_add;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu pp_menu_table;
    public javax.swing.JTable tbl_books;
    // End of variables declaration//GEN-END:variables
}
