/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Middlewares.FieldsValidator;
import Model.Book;
import Model.User;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ibarra
 */
public class DevolucionesForm extends javax.swing.JFrame {

    /**
     * Creates new form AddUsersForm
     */
    FieldsValidator validate = new FieldsValidator();

    public DevolucionesForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        txt_id_prestamo.requestFocus();
        this.txt_id_prestamo.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_id_prestamo = new javax.swing.JTextField();
        btn_add_user = new CustomComponents.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DEVUELVE EL LIBRO PRESTADO");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Id Prestamo");

        txt_id_prestamo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_id_prestamoKeyPressed(evt);
            }
        });

        btn_add_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book_plus.png"))); // NOI18N
        btn_add_user.setText("Devolver");
        btn_add_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_userActionPerformed(evt);
            }
        });
        btn_add_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_add_userKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(btn_add_user, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(txt_id_prestamo, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                        .addGap(35, 35, 35))))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_id_prestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_add_user, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addGap(52, 52, 52))
        );

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 170));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_add_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_userActionPerformed
        returnBook();

    }//GEN-LAST:event_btn_add_userActionPerformed

    private void txt_id_prestamoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_id_prestamoKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            btn_add_user.requestFocus();
        }
    }//GEN-LAST:event_txt_id_prestamoKeyPressed

    private void btn_add_userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_add_userKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            returnBook();
        }
    }//GEN-LAST:event_btn_add_userKeyPressed

    void returnBook() {
        Object[] array = {
            txt_id_prestamo
        };

        if (!validate.validateBlank(array)) {
            JOptionPane.showMessageDialog(this, "Rellena todos los campos");
            return;
        }
        Book book = new Book();

        try {
            book.returnBook(Integer.parseInt(txt_id_prestamo.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(DevolucionesForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        MainView.showJpanel(new DevolucionesView(true));

    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private CustomComponents.KButton btn_add_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt_id_prestamo;
    // End of variables declaration//GEN-END:variables
}
